In [47]:
import numpy as np
import sympy as sp
import arm2fk as fk
import arm2vk as vk





M = np.array([[0, 0, 1, 0],
              [0, 1, 0, 0],
              [-1, 0, 0, -.56825],
              [0, 0, 0, 1]])

S = np.array([[0, 1, 0],
              [-1, 0, -1],
              [0, 0, 0],
              [-.03825, 0, -.38825],
              [0, -.20825, 0],
              [0, 0, 0]])
theta0 = sp.symbols('theta0')
theta1 = sp.symbols('theta1')
theta2 = sp.symbols('theta2')

dh = np.array([[0, 0, -38.25, -np.pi/2],
               [theta0-np.pi/2, 170, 0, -np.pi/2],
               [theta1, 180, 0, np.pi/2],
               [theta2, 180, 0, -np.pi/2]])

def fkine(S,M,q):

    T = np.eye(4)
    for i in range(S.shape[1]):
        T = np.dot(T, twist2ht(S[:, i], q[i]))
    T = np.dot(T, M)
    return T

def twist2ht(twist, theta):
    twist = np.array(twist)
    omega = twist[0:3]
    v = twist[3:6]
    omega_hat = np.array([[0, -omega[2], omega[1]],
                          [omega[2], 0, -omega[0]],
                          [-omega[1], omega[0], 0]])
    R = np.eye(3) + np.sin(theta) * omega_hat + (1 - np.cos(theta)) * np.dot(omega_hat, omega_hat)
    p = np.dot((np.eye(3) * theta + (1 - np.cos(theta)) * omega_hat + (theta - np.sin(theta)) * np.dot(omega_hat, omega_hat)), v)
    T = np.eye(4)
    T[0:3, 0:3] = R
    T[0:3, 3] = p
    return T

def ikine(T):

    # print(T)
    # Set the bounds 
    lower_bound = -np.pi / 6 
    upper_bound = np.pi / 6 
    # # Generate a 3x1 random array within the specified bounds 
    q = (upper_bound - lower_bound) * np.random.rand(3) + lower_bound
    
     
    for i in range(1000000):
        # print(q)
        TG = fk.arm2fk(q[0],q[1],q[2])
        e = TG[0:3,3] - T[0:3,3]
        # print(T0)
        # print(e)
        # print(np.linalg.norm(e))
        if np.linalg.norm(e) < 1e-3:
            print("converged")
            print(q)
            print(TG)
            print(i)
            
            break
        J = vk.arm2vk(q[0],q[1],q[2]) #jacobian(S, q)

        # lambd = 0.1
        # dampedPseduoinv = np.linalg.pinv(J@J.T+lambd**2*np.eye(3))
        
        dq = np.linalg.pinv(J) @ np.vstack(e)
        q += dq.T[0]/1.5
        # print(q)
        
    
    
        
    return wrap_to_pi(q)



def wrap_to_pi(angle):
    return (angle + np.pi) % (2 * np.pi) - np.pi

def jacobian(S, q):
    J = np.zeros((6, S.shape[1]))
    T = np.eye(4)
    for i in range(S.shape[1]):
        T = T@twist2ht(S[:, i], q[i])
        Ad_T_Si = adjoint(T)@S[:, i]
        J[:, i] = Ad_T_Si
    return J

def adjoint(T): 
    """ Given a homogeneous transformation matrix T, calculate the corresponding 6x6 adjoint transformation matrix. """ 
    R = T[:3, :3] 
    p = T[:3, 3] 
    s = np.array([[0, -p[2], p[1]], 
                  [p[2], 0, -p[0]], 
                  [-p[1], p[0], 0]]) 
    AdT = np.block([[R, np.zeros((3, 3))],
                    [s @ R, R]]) 
    return AdT
            
def ht2twist(T):
    R = T[0:3, 0:3]
    p = T[0:3, 3]
    omega_hat = np.array([[0, -R[2, 1], R[1, 0]],
                          [R[2, 0], 0, -R[0, 2]],
                          [-R[1, 0], R[0, 1], 0]])
    omega = np.array([R[2, 1], R[0, 2], R[1, 0]])
    theta = np.arccos((np.trace(R) - 1) / 2)
    v = np.dot(np.linalg.inv(np.eye(3) * theta + (1 - np.cos(theta)) * omega_hat + (theta - np.sin(theta)) * np.dot(omega_hat, omega_hat)), p)
    twist = np.zeros(6)
    twist[0:3] = omega
    twist[3:6] = v
    return twist



def jacobe(S, M, q): 
    # Initialize the Jacobian matrix 
    J_b = np.zeros((6, len(q))) 
    # # Initialize the transformation matrix 
    T = np.eye(4) 
    B = S.copy() 
    # Loop through each joint 
    for i in range(len(q) - 1, -2, -1): 
        B[:, i] = twistspace2body(S[:, i], M) 
        # Update the transformation matrix 
        if i < len(q) - 1: 
            T = T @ twist2ht(B[:, i + 1], -q[i + 1]) 
            # Update the Jacobian matrix           
            J_b[:, i] = adjoint(T) @ B[:, i]
    return J_b

def skew(vector):
    """Create a skew-symmetric matrix from a 3-vector."""
    return np.array([[0, -vector[2], vector[1]],
                     [vector[2], 0, -vector[0]],
                     [-vector[1], vector[0], 0]])

def twistspace2body(V_s, T):
    """
    Convert a twist from the space frame to the body frame.
    
    Parameters:
    V_s -- Twist in the space frame (6x1 numpy array).
    T -- Homogeneous transformation matrix from the body frame to the space frame (4x4 numpy array).
    
    Returns:
    V_b -- Twist in the body frame (6x1 numpy array).
    """
    # T is the homogeneous transformation matrix from the body frame to the space frame
    R = T[:3, :3]  # Rotation matrix
    p = T[:3, 3]   # Position vector
    Adj_T = np.block([[R, skew(p) @ R], [np.zeros((3, 3)), R]])  # Adjoint representation of T
    V_b = Adj_T.T @ V_s
    return V_b


q0=[np.pi/3,0,np.pi/6]
T=fk.arm2fk(q0[0],q0[1],q0[2])
print("Init angle",q0)
print("Goal Pos",T)
q=ikine(T)
T2=fk.arm2fk(q[0],q[1],q[2])

print("IK angles",q)
print("IK angles Fk",T2)
# J=jacobian(S,[0,0,0])
# Je=jacobe(S,M,[0,0,0*np.pi/2])
# print(vk.arm2vk(q0[0],q0[1],q0[2]))
# print(Je)

Init angle [1.0471975511965976, 0, 0.5235987755982988]
Goal Pos [[ 1.00000000e+00 -0.00000000e+00  2.22044605e-16  4.83108891e-01]
 [ 0.00000000e+00  1.00000000e+00 -0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  0.00000000e+00  1.00000000e+00 -2.13250000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
IK angles [-0.64109893  0.15283236  2.38390386]
IK angles Fk [[ 0.98017884  0.09105002 -0.17595262 -0.03163976]
 [-0.11058975  0.98834385 -0.10462476  0.0074967 ]
 [ 0.16437561  0.12200954  0.97882293 -0.28748454]
 [ 0.          0.          0.          1.        ]]
